# Site settings
title: Jakobi Talbot
description: Jakobi Talbot's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jakobi Talbot
user_description: Hi! My name is Jakobi, I'm a game programmer who is currently studying at AIE Melbourne and will be graduating in 2019.
user_title: Game Programmer
email: jakobi.talbot@gmail.com
twitter_username: JakobiKT
github_username:  JakobiTalbot

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
